setwd("D:/Module4")
household<- read.table("household_power_consumption.txt",header = TRUE, sep = ";", stringsAsFactors=FALSE, dec=".")
Febhousehold <- household[household$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(Febhousehold$Date, Febhousehold$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(Febhousehold$Global_active_power)
subM1 <- as.numeric(Febhousehold$Sub_metering_1)
subM2 <- as.numeric(Febhousehold$Sub_metering_2)
subM3 <- as.numeric(Febhousehold$Sub_metering_3)

png("Plot3.png", width=480, height=480)
plot(datetime, subM1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subM2, type="l", col="red")
lines(datetime, subM3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=2, lwd=3, col=c("black", "red", "blue"))
dev.off()
